baseURL = "https://whereistand.xyz"
theme = "LoveIt"
title = "在场"

defaultContentLanguage = "zh-cn"
languageCode = "zh-CN"
defaultContentLanguageInSubdir = true
contentDir = "content/zh-cn"



# copyright description used only for seo schema
copyright = "© All rights reserved."

# whether to use robots.txt
enableRobotsTXT = true

# whether to use git commit log
enableGitInfo = false

# whether to use emoji code
enableEmoji = true

# Pagination config

# [pagination]
#     disableAliases = false
#     pagerSize = 10
#     path = "page"

[outputs]
    home = ["HTML", "RSS", "JSON"]


[params]
    defaultTheme = "auto"

    [params.typeit]
        speed = 90
        cursorSpeed = 900
        cursorChar = "|"
        duration = -1

    # Author config
    # 作者配置
    [params.author]
        name = "Joey"
        email = "jihui.yang0.0@gmail.com"
        link = "https://whereistand.xyz"

    # Header config
    # 页面头部导航栏配置
    [params.header]
        desktopMode = "fixed"
        mobileMode = "auto"
            # 主页左上角主页名称和logo
        [params.header.title]
            logo = "/images/logo.png"
            name = "在场"
            pre = ""
            post = " · Where I Stand"
            typeit = false

    # Footer config
    # 页面底部信息配置
    [params.footer]
        enable = true
        custom = "事情不尽然如此 / Against Easy Answers"
        hugo = false
        copyright = true
        author = true
        since = 2025
        icp = ""
        license = ""

    # Section (all posts) page config
    # Section (所有文章) 页面配置
    [params.section]
        paginate = 10
        dateFormat = "01-02"
        rss = 10

    # List (category or tag) page config
    # List (目录或标签) 页面配置
    [params.list]
        paginate = 20
        dateFormat = "01-02"
        rss = 10
    
    # Home page config
    # 主页信息设置
    [params.home]
        # amount of RSS pages
        # RSS文章数量
        rss = 10
        # Home page profile
        # 主页个人信息
    
    # Social config in home page
    # 主页的社交信息设置
    [params.social]
        Email = "jihui.yang0.0@gmail.com"
        RSS = true
    
    [params.page]
        hiddenFromHomePage = false
        hiddenFromSearch = false
        lightgallery = true
        ruby = true
        fraction = true
        fontawesome = true
        linkToMarkdown = true
        rssFullText = false
        
        # 目录
        [params.page.toc]
            enable = true
            keepStatic = false
            auto = true

        [params.page.code]
            copy = true
            maxShownLines = 50
            [params.page.code.render]
                goat = false
                mermaid = false
        
        # [params.page.mapbox]

        # 分享信息设置
        [params.page.share]
            enable = true
            X = true
            Facebook = true
            Linkedin = true 
            Whatsapp = true

        # 评论区设置
        [params.page.comment]
            enable = false

    # 搜索栏
    [params.search]
        enable = true
        type = "lunr"
        contentLength = 4000
        placeholder = "Search..."
        maxResultLength = 10
        snippetLength = 30
        highlightTag = "em"
        absoluteURL = false

    # App icon config
    # 应用图标配置
    [params.app]
        title = ""
        noFavicon = false
        svgFavicon = ""
        themeColor = "#ffffff"
        iconColor = "#5bbad5"
        tileColor = "#da532c"


    # 必须关掉这俩货，防止报错
    # [params.page.code.render]
    #     goat = false
    #     mermaid = false

# --- 语言定义 ---
[languages]

    # === 1. 中文配置 ===
    [languages.zh-cn]
        weight = 1
        languageCode = "zh-CN"
        languageName = "简体中文"
        title = "在场"
        # contentDir = "content/zh-cn"

        # 中文主页显示最近文章
        [languages.zh-cn.params.home]
            rss = 10

            [languages.zh-cn.params.home.posts]
                enable = true
                paginate = 6

        # 中文主页信息 (修复黑白切换的关键)
        [languages.zh-cn.params.home.profile]
            enable = true
            avatarURL = "/images/avatar.png"
            title = "在场"
            subtitle = "事情不尽然如此"
            typeit = true
            social = true
        
        [languages.zh-cn.params.search]
            enable = true
            type = "lunr"
            contentLength = 4000
            placeholder = "搜索..."
            maxResultLength = 10
            snippetLength = 30
            highlightTag = "em"
            absoluteURL = false

        # 中文菜单
        [languages.zh-cn.menu]
            [[languages.zh-cn.menu.main]]
                weight = 1
                identifier = "posts"
                name = "所有文章"
                url = "posts/"
            
            [[languages.zh-cn.menu.main]]
                weight = 2
                identifier = "categories"
                name = "分类"
                url = "categories/"

            [[languages.zh-cn.menu.main]]
                weight = 3
                identifier = "about"
                name = "关于我"
                url = "about/"
        
    # === 2. 英文配置 ===
    [languages.en]
        weight = 2
        languageCode = "en"
        languageName = "English"
        title = "Where I Stand"
        contentDir = "content/en"

        [languages.en.params.home]
            rss = 10

            [languages.en.params.home.posts]
                enable = true
                paginate = 6

        # 英文主页信息 (强制覆盖 My Cool Site)
        [languages.en.params.home.profile]
            enable = true
            avatarURL = "/images/avatar.png"
            title = "Where I Stand"
            subtitle = "Against Easy Answers"
            typeit = true
            social = true

        [languages.en.params.search]
            enable = true
            type = "lunr"
            contentLength = 4000
            placeholder = "Search..."
            maxResultLength = 10
            snippetLength = 30
            highlightTag = "em"
            absoluteURL = false


        # 英文菜单
        [languages.en.menu]
            [[languages.en.menu.main]]
                weight = 1
                identifier = "posts"
                name = "All posts"
                url = "posts/"

            [[languages.en.menu.main]]
                weight = 2
                identifier = "categories"
                name = "Categories"
                url = "categories/"

            [[languages.en.menu.main]]
                weight = 3
                identifier = "about"
                name = "About Me"
                url = "about/"
